### ISSUE TITLE
Presentation software

### ISSUE THREAD

**Issue by Luke-lwz** [motion-canvas/motion-canvas#254] opened 2023-02-08 17:38 UTC
**Description**
Hi, this is more of a vague idea.
I think it would be awesome to be able to use this as a presentation software.

**Proposed solution**
My proposal would be:
Add the ability to render the preview from the editor in a new window so that cou can present it in fullscreen.
Give the ability to place "presentation points" on the timeline to which the animation will run and then stop and wait for a button press, to then leave for the next "presentation point".

**Additional context**
I'm a student and I'd love to use this as my presentation software

**Comment by Luke-lwz** [comment] 2023-02-08 17:41
**Additional Note**
Maybe instead of "presentation points" there could be a function like:
`yield* waitForButtonPress()`

this would of course leave an issue with not being able to go back to a previous "slide"

**Comment by Tandashi** [comment] 2023-02-08 19:24
Looks like a duplicate of #213

**Closed** 2023-02-09 04:05 UTC
Labels: c-duplicate
