### ISSUE TITLE
Issue with Text opacity below 1 causing text to clip with some strings

### ISSUE THREAD

**Issue by dct-LuLu** [motion-canvas/motion-canvas#370] opened 2023-02-18 10:49 UTC
**Describe the bug**
When reducing the opacity of a Text Node, certain character in the strings are cut off, resulting in display issues. This occurs when there are multiple consecutive spaces, when the character string begins with at least a space, or when there is a lowercase 'f' character in the string.

**Steps to Reproduce**

1. Create a new Text ref, add it to view, and link it with the ref.
2. Set the opacity of the Text Node to 1.
3. Type the following strings into the Text Node:

- "hello  world" (multiple consecutive spaces)
- " space before" (string begins with a space)
- "off" (contains lowercase 'f' character)

4. Edit the signal after some time of the Text to lower the opacity. This should work at any values below 1.
5. Observe the text in the video.

```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { createRef } from '@motion-canvas/core/lib/utils';
import { Text } from '@motion-canvas/2d/lib/components';
import { waitUntil } from '@motion-canvas/core/lib/flow';


export default makeScene2D(function* (view) {
	// Create a Text ref
	const test = createRef<Text>();

	// Add the Text Node to the view
	view.add(
		<>
		<Text
			ref={test}
			text={'hello  world'}
			fill={'#fff'}
		/>
		</>
	);

		// Wait until the "before" event
		yield* waitUntil("before");

		// Lower the opacity of the Text Node
		yield* test().opacity(0.1, 1);

		// Wait until the "after" signal
		yield* waitUntil("after");
});
```

**Expected Result**
The text should be displayed clearly and legibly, regardless of opacity settings or the specific characters used in the string.

**Actual Result**
The text is cut off at the end of the string, making it difficult to read or understand and causes weird transition.

**Console errors**
 No errors anywhere.

**Package versions**

- core: [2.3.0]
- ui: [2.3.0]

**Additional Information**
Changing the font size or line height does not seem to fix the issue. This issue is especially annoying when attempting to create a fade-out effect with text. It is not necessary for it to be a transition if we set the base opacity at a value under 1 the clipping is already displayed.

Please let me know if you need any further information or clarification.

**Comment by aarthificial** [comment] 2023-02-18 11:26
We'll see if we can fix that.
In the meantime: The issue is caused by the renderer using HTML to lay out the text. This means that whitespaces follow the same rules as in HTML (more than one space is merged into one etc.). For some reason, we try to render the provided text one-to-one, while using the bounding box of the HTML text. 
If you need to preserve the white spaces, you can use `textWrap={'pre'}`, this could be a workaround.

**Closed** 2023-02-18 11:48 UTC
Labels: b-bug, c-accepted, a-2d

**Comment by dct-LuLu** [comment] 2023-02-18 12:38
> We'll see if we can fix that. In the meantime: The issue is caused by the renderer using HTML to lay out the text. This means that whitespaces follow the same rules as in HTML (more than one space is merged into one etc.). For some reason, we try to render the provided text one-to-one, while using the bounding box of the HTML text. If you need to preserve the white spaces, you can use `textWrap={'pre'}`, this could be a workaround.

Thank you for this solution regarding whitespaces. However, I'm still curious about the string with "f". It's a minor issue, but it detracts from the overall aesthetic.

**Comment by aarthificial** [comment] 2023-02-18 12:52
> "off" (contains lowercase 'f' character)

Missed that part.
Can you provide an example to reproduce this?
Just changing the text to `off` in the example above works fine.

**Comment by dct-LuLu** [comment] 2023-02-21 17:37
> > "off" (contains lowercase 'f' character)
> 
> Missed that part. Can you provide an example to reproduce this? Just changing the text to `off` in the example above works fine.

The above example does this for me. It's barely noticeable, but with a bigger font, we can clearly see it. In fact, it only happens when there's an 'f' at the end of the string.

![issue](https://user-images.githubusercontent.com/69580109/220418455-f19ea85b-05a9-455f-8be0-1b9065ed107b.gif)
