### ISSUE TITLE
External images can't render

### ISSUE THREAD

**Issue by trolol2** [motion-canvas/motion-canvas#412] opened 2023-02-24 12:52 UTC
**Describe the bug**
When trying to render, if an image from an external source is in the scene, an error occurs.

**To Reproduce**
Add an image to a scene, with the src being an external link to an image, for example: https://img.icons8.com/fluency/256/oak-leaf.png

**Expected behavior**
Render without a problem

**Console errors**
![image](https://user-images.githubusercontent.com/31692830/221183091-b665bc1e-df73-43ce-81aa-1bfa94525c45.png)

**Package versions (please complete the following information):**

- core: 2.1.0
- ui: 2.1.0

**Comment by aarthificial** [comment] 2023-02-24 13:05
A duplicate of #338
Will be fixed in `v2.6.0`

**Closed** 2023-02-24 13:49 UTC
Labels: c-duplicate
