### ISSUE TITLE
Code Error Highlighting

### ISSUE THREAD

**Issue by pedrobzz** [motion-canvas/motion-canvas#278] opened 2023-02-09 18:10 UTC
**Description**
As a developer, I want a way to highlight code errors in my `CodeBlock` component, similar to how my IDE does. I'm not proposing to build a compiler, but a simple API that will allow me to highlight errors.

**Proposed solution**
I propose adding a new function to the `CodeBlock` component, similar to the selection function. For example, to select lines, we currently do the following:
```typescript
yield* code().selection(range(0, 0, 0, 10), 0.3);
```

Similarly, I would like to have a function to highlight errors, like this:
```typescript
yield* code().error(range(0, 0, 0, 10), 0.3);
```

**Considered alternatives**
I considered drawing a rectangle to highlight errors, but I prefer not to use absolute positioning every time I want to highlight an error.

**Additional context**

This feature is one of three necessary components for my use case, and it is the easiest to implement. I believe that if I can find a way to do this by creating a custom CodeBlock, I will be able to understand and implement the other two on my own.

**Comment by hhenrichsen** [comment] 2023-02-09 18:18
Probably a duplicate of #258, I filed that for you and another user.

**Comment by pedrobzz** [comment] 2023-02-09 18:27
Thanks @hhenrichsen, I wasn't able to create it yesterday, but I appreciate that you did! I'm not sure if I should close this issue, but I would really appreciate it if someone could help me understand how to implement this. That way, I can fully transition to Motion-Canvas and implement the features I want, as well as assist others in adopting the platform.

I've created a forum post if anyone is interested in this topic.
https://discord.com/channels/1071029581009657896/1073305650140037162/1073305650140037162

**Closed** 2023-02-10 06:27 UTC
