### ISSUE TITLE
Draggable timeline playhead

### ISSUE THREAD

**Issue by misclicl** [motion-canvas/motion-canvas#658] opened 2023-05-09 08:40 UTC
**Description**

While using the app, I try to intuitively drag the playhead controller with my cursor all the time, but it’s impossible. Do you think it would be feasible to add this feature? I haven't checked the code yet, so I'm not sure how hard it is.

**Proposed solution**

I can only give a basic visual suggestion at this point, such as adding a hover state, while allowing the user to drag the playhead controller:

<img width="552" alt="Screenshot 2023-05-09 at 11 37 41" src="https://user-images.githubusercontent.com/84678137/237042060-eaa68efa-5ff0-4fb6-9a2c-781f657009db.png">

**Comment by aarthificial** [comment] 2023-05-09 09:55
Duplicate of #286

**Closed by aarthificial** 2023-05-09 09:55 UTC
