### ISSUE TITLE
How to place an animation in an existing web project

### ISSUE THREAD

**Issue by dinchu** [motion-canvas/motion-canvas#996] opened 2024-03-16 13:20 UTC
After reading all the docs I couldn't find a single example on how to add the animations to a website or an existing js project built with vue. It would be good to have simple examples on how to place the player in the desired place and how to interact with frontend libraries/frameworks such as Vue, react or Angular

**Comment by dinchu** [comment] 2024-03-21 14:08
Is there a way to render a player with the animation that can be used in other projects? or the idea is only to make the animations in a dev/local env with the timeline and export the results as a gift/video?

**Comment by aarthificial** [comment] 2024-03-21 15:13
Yes, you can take a look at #443
I'm closing this as a duplicate of #247

**Closed by aarthificial** 2024-03-21 15:13 UTC
Labels: b-documentation

**Comment by dinchu** [comment] 2024-03-24 21:56
I followed #443 #247
but the solution didn't work, i get an "An error occurred while loading the animation." in the UI
I double checked and the Js file compilded is loaded and reachable in the browser

**Comment by neilkinnish** [comment] 2024-06-01 13:42
@dinchu possibly you have ffmpeg as part of the vite plugin list and it's code is bundled. If you remove the plugin on build it should be playable (at least in Chrome I think).

**Comment by Krixtalx** [comment] 2024-06-15 00:17
@neilkinnish you did my week, thanks!

**Comment by sneha25032001** [comment] 2025-03-08 20:02
@neilkinnish @Krixtalx @aarthificial 
I tried building the project and then used the js file inside my React project using motion-canvas-player but in browser it gives me below error. I have already tried building the project after removing ffmpeg from vite plugin list but it didn't make any difference. Any possible solutions?

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/bf0e2905-e168-455f-971e-c2cf60430969" />

**Comment by mesons-web** [comment] 2025-03-08 20:17
@neilkinnish @aarthificial @dinchu @Krixtalx 
I tried building the animation and put it in my React project. Used motion-canvas-player as mentioned and gave path of js file in it but it is giving below error. I have also tried removing ffmpeg plugin from vite plugin list  and building but it does not make any difference. Any possible solutions?

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/86aa2d2e-5b8a-4252-a9a5-0715a3f36cc2" />

<img width="699" alt="Image" src="https://github.com/user-attachments/assets/840962b3-0a26-45a7-b8d7-b0807d922ac8" />

**Comment by prathje** [comment] 2025-06-06 16:27
Hey @mesons-web, I've managed to create a small demo that bundles the player and core packages. Maybe that demo might be helpful?

https://github.com/prathje/motion-canvas-player-dist
