### ISSUE TITLE
bug: shadowBlur + scale blurs children

### ISSUE THREAD

**Issue by DanielBreiner** [motion-canvas/motion-canvas#343] opened 2023-02-14 14:21 UTC
Title. Tested in Firefox and Chrome, seems to be behaving the same.

```ts
import { Rect, Text } from "@motion-canvas/2d/lib/components";
import { makeScene2D } from "@motion-canvas/2d/lib/scenes";
import { waitFor } from "@motion-canvas/core/lib/flow";

export default makeScene2D(function* (view) {
  view.add(
    <Rect
      fill="white"
      size={[200, 200]}
      shadowBlur={10}  // Without either shadowBlur or scale looks fine
      scale={5} 
    >
      <Text text="I'm blurred :(" />
    </Rect>
  );
  yield* waitFor(5);
});
```

Version 2.3.0

**Comment by aarthificial** [comment] 2023-02-15 15:54
Closing this as a duplicate of #342 because it's the same underlying problem

**Closed by aarthificial** 2023-02-15 15:54 UTC
