### ISSUE TITLE
Erroneous behaviour when using the Camera component

### ISSUE THREAD

**Issue by Omixxx** [motion-canvas/motion-canvas#1130] opened 2024-11-10 11:34 UTC
**Describe the bug**
I get an unexpected behaviour when using the camera object. In this example, once the camera component has been added as root, the animation of increasing the opacity of the two SVG's no longer exists, and they simply appear. 
In addition, when I zoom in on the text, I get a whole series of anomalous behaviour that I do not get if I remove the camera component: 
when I change the phrase from ‘Does adding more crayons’ to ‘prevent you from drawing?’ the text jumps up a little, and also, when I try to change the opacity the text gets completely bugged. 
Am I doing something wrong?

**To Reproduce**

```ts
import {Camera, Circle, Line, makeScene2D, Rect, Spline, SVG, Txt} from "@motion-canvas/2d";
import {all, chain, createRef, delay, loop, sequence} from "@motion-canvas/core";
import redCrayonSvg from "../assets/crayon_red.svg?raw"
import greenCrayonSvg from "../assets/crayon_green.svg?raw"
import {Utils} from "../../utils/Utils";

export default makeScene2D(function* (view) {

    const utils = new Utils()
    const camera = createRef<Camera>()
    const spline = createRef<Spline>()
    const draw = createRef<Rect>()
    const crayonRoot = createRef<Rect>()
    const redCrayon = createRef<SVG>()
    const greenCrayon = createRef<SVG>()
    const circle = createRef<Circle>()
    const text = createRef<Txt>()

    view.fill("white")

    view.add(
        <Camera ref={camera}>
            <Rect ref={crayonRoot} position={[-400, -300]} layout>
                <SVG ref={redCrayon} svg={redCrayonSvg} rotation={-45} size={200} opacity={0}></SVG>
                <SVG ref={greenCrayon} svg={greenCrayonSvg} rotation={-45} size={200} opacity={0}></SVG>
            </Rect>

            <Circle ref={circle} position={crayonRoot().position()} fill={"black"}
                    size={0}></Circle>

            <Rect ref={draw} start={0} end={0} lineWidth={3} stroke={"black"} size={100} lineDash={[10, 10]}/>
            <Line ref={spline} lineWidth={5} endArrow endOffset={10} lineDash={[40, 12]} stroke={"black"}
                  start={0}
                  end={0}
                  radius={1000}
                  points={[
                      circle().bottom(),
                      [circle().bottom().x, draw().left().y],
                      draw().left()
                  ]}
            />
            <Txt fontFamily={"Noto Sans"} fontSize={70} fontWeight={20} ref={text} y={100}></Txt>
        </Camera>
    )

    yield* all(
        redCrayon().opacity(1, 1,),
        greenCrayon().opacity(1, 1,),
        delay(1, all(
                circle().size(20, 1),
                spline().end(1, 1),
                delay(0.6,
                    chain(
                        draw().end(1, 1),
                        draw().fill("lightGray", 0.2)
                    )
                )
            )
        )
    )


    yield* loop(5, () => {
        let targetOpacity = draw().opacity() == 1 ? 0 : 1
        return delay(0.3, draw().opacity(targetOpacity, 0))
    })

    yield* sequence(0.5,
        spline().end(0, 1),
        circle().size(0, 1),
    )

    yield* chain(
        all(
            camera().centerOn(text(), 1),
            camera().zoom(2, 1)
        ),
        text().text("Does adding more crayons", 1),
        text().text("prevent you from drawing?", 1),
        text().opacity(0, 1),
    )
});

```

**Expected behavior**
the one described by the animations without strange artefacts

**Console errors**
There are no console errors

**Package versions:**

- core: 3.17.0
- two: 3.17.1
- ui: 3.17.0
- vitePlugin: 3.17.0

https://github.com/user-attachments/assets/53a224a4-09f7-4324-b215-667161013eb7

**Comment by aarthificial** [comment] 2024-12-14 21:27
Sadly this is a duplicate of #1057 that's yet to be fixed

**Closed by aarthificial** 2024-12-14 21:27 UTC
Labels: b-bug
