### ISSUE TITLE
Issue with drawing CodeBlock selection

### ISSUE THREAD

**Issue by t3ssel8r** [motion-canvas/motion-canvas#229] opened 2023-02-07 05:26 UTC
**Describe the bug**
Incorrect parts of the code are highlighted using `CodeBlock.selection`

**To Reproduce**
```ts
import {makeScene2D} from '@motion-canvas/2d';
import {waitUntil} from '@motion-canvas/core/lib/flow';
import {createRef} from '@motion-canvas/core/lib/utils';

import {
  CodeBlock,
  edit,
  word,
} from '@motion-canvas/2d/lib/components/CodeBlock';

export default makeScene2D(function* (view) {
    const code = createRef<CodeBlock>();
    view.add(
        <CodeBlock
            ref={code}
            language={'hlsl'}
            code={() => `float y = (sin(a)) * b;`}
        />
    );
    yield* code().selection(word(0, 10, 8), 1);
    yield* code().edit(1)`float y = ${edit('(sin(a))', '(cos(a))')} * b;`;
});
```

**Expected behavior**

1. `float y = (sin(a)) * b;` gets added
2. `(sin(a))` gets highlighted
3. `(sin(a))` gets replaced with `(cos(a))`, which gets highlighted

**Actual behavior**

1. `float y = (sin(a)) * b;` gets added
2. `sin(a)) * b;` gets highlighted
3. highlighting suddenly switches to `(sin(a))` and gets replaced with `(cos(a))`, which gets highlighted

**Package versions (please complete the following information):**

- core: 2.0.0
- ui: 2.0.0

**Additional context**
Changing the language type causes the behavior to change, but does not resolve the issue. I suspect the issue is between `CodeBlock.draw` and `CodeBlock.selectionStrength`, but don't know enough typescript to be able to understand what went wrong.

**Comment by hhenrichsen** [comment] 2023-02-07 05:44
I'm looking into this.

**Comment by hhenrichsen** [comment] 2023-02-07 05:59
Another repro example from the Discord:
```tsx
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { CodeBlock, range, insert, edit } from '@motion-canvas/2d/lib/components/CodeBlock';
import { waitFor } from '@motion-canvas/core/lib/flow';
import { createRef } from '@motion-canvas/core/lib/utils';

export default makeScene2D(function* (view) {
    const body = createRef<CodeBlock>();

    view.add(
        <CodeBlock ref={body} language="rs">
            {`pub async fn save() {}`}
        </CodeBlock>,
    );

    yield* waitFor(2);

    yield* body().edit(2)`pub async fn save(${insert('name: String, age: usize')}) {}`;

    // as soon as the duration of 2 above completes,
    // the first part of the insert, `name:` de-highlights,
    // however the rest, `String, age: usize` stays highlighted

    yield* waitFor(2);

    yield* body().edit(2, range(0, 18, 0, 42))`pub async fn save(name: String, age: usize) {}`;

    // the same result occurs even when specifying a custom CodeRange

    yield* waitFor(2);

    yield* body().edit(2)`pub async fn save(${edit('name: String, age: usize', 'why hello there name String, age usize')}) {}`;

    // as soon as above edit completes,
    // the first part of the edit up to the colon, `why hello there name:`, de-highlights,
    // however the rest, `String, age: usize` stays highlighted

    yield* waitFor(2);

    yield* body().edit(2)`pub async fn save(${edit('name: String, age: usize', 'why hello there name String, age usize')}) {}`;

    // as soon as above edit completes,
    // the exact same chunk of code de-highlights, `why hello there name`, even though there i no colon anymore
    // somehow the highlighting keeps picking up as of `String` :(

    yield* waitFor(2);
});
```

Both are throwing the following error when constructing the scene, based on the `CodeBlock`'s initialization computed property:
```
Tried to access an asynchronous property before the node was ready. Make sure to yield the node before accessing the property.
```

**Comment by aarthificial** [comment] 2023-02-07 07:08
> Tried to access an asynchronous property before the node was ready. Make sure to yield the node before accessing the property.

It's weird that the stack trace doesn't show where the problem comes from, but `CodeBlock` is an asynchronous node, so before tweening the code, we need to yield it - this will wait for all the async resources to load. We can do that immediately during the addition, which solves the above issue:
```ts
yield view.add(
    <CodeBlock
        ref={code}
        language={'hlsl'}
        code={() => `float y = (sin(a)) * b;`}
    />
);
```

But the real problem with these two snippets is the highlighting, which is caused by the fact that we highlight code by entrie tokens. In @t3ssel8r example, for instance, `(a)) * b;` is treated as one token (the highlighter we use groups characters based on style and not on the language syntax) so it can only be either entirely highlighted or not.

The fix for this is already in the source code, but I forgot to remove the if statements for it to work. Here:
https://github.com/motion-canvas/motion-canvas/blob/3437e42713a3f4a8d44d246ee01e2eb23b61e06a/packages/2d/src/components/CodeBlock.ts#L315
And here:
https://github.com/motion-canvas/motion-canvas/blob/3437e42713a3f4a8d44d246ee01e2eb23b61e06a/packages/2d/src/components/CodeBlock.ts#L404

**Closed** 2023-02-07 10:11 UTC
Labels: b-bug, c-accepted, a-2d
