### ISSUE TITLE
Error to run built animations

### ISSUE THREAD

**Issue by dsmtE** [motion-canvas/motion-canvas#1104] opened 2024-08-31 17:20 UTC
**Describe the bug**

I try to run exported animations on my website( using the player "@motion-canvas/player" ) but i encountered this issue with exported js files:

```bash
main.js:140 ReferenceError: Cannot access 'Ht' before initialization
    at _virtual_settings-3f31c895.js:312:18
```

**To Reproduce**

I just export my animations using `npm run build` copy built files in my website ( in static folder) and run those.

 [Here](https://github.com/user-attachments/files/16825503/Built_file_for_repro.zip) my built files if needed for a repro.

**Tests & Workaround**

I tried to understand what going on, diging throught the minified exported file.

It seems to come from an error in the order of the exported class in the file:

I found a workaround to make it work by interverting this class and declaration in the file (move then up before declaration of an other class that extends from `Ht`);

```ts
class Zu extends Ct {
  get onFieldsChanged() {
    return this.event.subscribable
  }
  constructor(t, e) {
    const r = new Map(Object.entries(e))
    super(t, Object.fromEntries(Array.from(r, ([i, a]) => [i, a.get()]))),
      (this.type = Object),
      (this.ignoreChange = !1),
      (this.customFields = {}),
      (this.handleChange = () => {
        this.ignoreChange ||
          (this.value.current = {
            ...this.transform("get"),
            ...this.customFields
          })
      }),
      (this.event = new we([...r.values()])),
      (this.fields = r)
    for (const [i, a] of this.fields)
      Object.defineProperty(this, i, { value: a }),
        a.onChanged.subscribe(this.handleChange)
  }
  set(t) {
    this.ignoreChange = !0
    for (const [e, r] of Object.entries(t)) {
      const i = this.fields.get(e)
      i ? i.set(r) : (this.customFields[e] = r)
    }
    ;(this.ignoreChange = !1), this.handleChange()
  }
  serialize() {
    return { ...this.transform("serialize"), ...this.customFields }
  }
  clone() {
    const t = new this.constructor(this.name, this.transform("clone"))
    return t.set(structuredClone(this.customFields)), t
  }
  transform(t) {
    return Object.fromEntries(Array.from(this.fields, ([r, i]) => [r, i[t]()]))
  }
}
const Ht = Zu
```

And the problematic class (that extends from Ht):
```ts
class pu extends Ht {
  constructor(t) {
    super("project", du(t))
  }
  getFullPreviewSettings() {
    return { ...this.shared.get(), ...this.preview.get() }
  }
  getFullRenderingSettings() {
    return { ...this.shared.get(), ...this.rendering.get() }
  }
}
```

**Package versions:**
*Click on the version in the bottom right corner to copy the versions*

- core: [3.16.0]
- ui: [3.16.0]
( also tested in 3.17.1 and same issue)
- typescript : [5.2.2]
- vite : [4.5.3]

**Additional context**
My website run using docusaurus with this packages versions:

- docusaurus: [3.4.0]
- typescript : [5.3.3]
- motion-canvas: [same as my export project]

**Comment by Moumirrai** [comment] 2024-10-22 20:15
I ran into the same problem. 

`Uncaught ReferenceError: Cannot access 'ObjectMetaField' before initialization`
```js
class ProjectMetadata extends ObjectMetaField {
  constructor(project2) {
    super("project", createProjectMetadata(project2));
  }
  getFullPreviewSettings() {
    return {
      ...this.shared.get(),
      ...this.preview.get()
    };
  }
  getFullRenderingSettings() {
    return {
      ...this.shared.get(),
      ...this.rendering.get()
    };
  }
}
````

**Package versions:**

- core: 3.17.0
- two: 3.17.1
- ui: 3.17.0
- vitePlugin: 3.17.0
- typescript: 5.6.3
- vite: 4.5.5

**Comment by aarthificial** [comment] 2024-12-14 17:11
Sorry for the late response.
Could one of you provide the original scene file that produces this error?
It's caused by rollup incorrectly piecing the imports together, however, it seems to only happen when specific modules are used.
Having a scene that causes this would greatly help with debugging and fixing it.

**Comment by Moumirrai** [comment] 2024-12-14 17:36
Hi, what I tried so the error occurs for me even with the default unmodified scene.

To reproduce:
```
npm init @motion-canvas@latest //all left on default
cd myproject
npm install
npm run build
```

Then when trying to load resulting js file in browser i get
```
PresenterComponent.vue:62 ReferenceError: Cannot access 'Xt' before initialization
    at project-18280ef8.js:3:2188
```

**Comment by Moumirrai** [comment] 2024-12-14 17:42
Sorry, I forgot to turn off minification. Without it, the error message is again
```
ReferenceError: Cannot access 'ObjectMetaField' before initialization
    at project-b0cc839b.js:459:31
```

**Comment by aarthificial** [comment] 2024-12-14 20:31
Can you try updating `core` to version `3.17.2` and see if the problem has been fixed?

**Comment by Moumirrai** [comment] 2024-12-14 20:48
Updating to core version 3.17.2 fixed the issue for me. Thank you so much for resolving this! I really appreciate it.

Thanks again!

**Comment by aarthificial** [comment] 2024-12-14 20:56
That's great to hear! I'm closing the issue for now.

@dsmtE feel free to reopen if the problem still occurs.

**Closed by aarthificial** 2024-12-14 20:56 UTC
Labels: b-bug, c-accepted, a-player
