### ISSUE TITLE
Error when using Circle without fill: Cannot use 'in' operator to search for 'lerp' in null

### ISSUE THREAD

**Issue by cozek** [motion-canvas/motion-canvas#260] opened 2023-02-09 05:00 UTC
**Describe the bug**
Cannot fill color of circle if color not provided when creating the circle.

**To Reproduce**
Steps to reproduce the behavior
or a code snippet containing the scene that causes the problem:

```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { Circle } from '@motion-canvas/2d/lib/components';
import { createRef } from '@motion-canvas/core/lib/utils';
import { all } from '@motion-canvas/core/lib/flow';

export default makeScene2D(function* (view) {
  const myCircle = createRef<Circle>();

  view.add(
    <Circle
      ref={myCircle}
      x={-300}
      width={240}
      height={240}
      // fill="#e13238" // code does not work without the fill.
    />,
  );

  yield* all(
    myCircle().position.x(300, 1).to(-300, 1),
    myCircle().fill('#e6a700', 1).to('#e13238', 1),
  );
});
```

**Expected behavior**
The circle should get the desired color filled.

**Console errors**
```
Cannot use 'in' operator to search for 'lerp' in null
The problem occurred here:
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:3777:14)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4220:16)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:3876:7)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4219:12)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4214:17)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4204:11)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4346:32)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4396:29)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4762:30)
at (/node_modules/.vite/deps/chunk-B6VKP7M3.js:4743:18)
at (/node_modules/.vite/deps/chunk-D2ST3UEE.js:492:7)
at (/node_modules/.vite/deps/@motion-canvas_ui.js:194:7)
at (/node_modules/.vite/de
```

**Package versions (please complete the following information):**

```
{
  "name": "my-animation",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "serve": "vite",
    "build": "tsc && vite build"
  },
  "dependencies": {
    "@motion-canvas/core": "^2.1.0",
    "@motion-canvas/2d": "^2.1.0"
  },
  "devDependencies": {
    "@motion-canvas/ui": "^2.1.0",
    "@motion-canvas/vite-plugin": "^2.1.0",
    "vite": "^3.0.5"
  }
}
```

**Additional context**
This example is listed in the docs, but does not work as intended.
https://motion-canvas.github.io/docs/flow

**Comment by aarthificial** [comment] 2023-02-09 06:02
Duplicate of #243

**Closed by aarthificial** 2023-02-09 06:02 UTC
