### ISSUE TITLE
Export the rendered output to mp4

### ISSUE THREAD

**Issue by mohsinhijazee** [motion-canvas/motion-canvas#422] opened 2023-02-26 12:25 UTC
**Description**
More of a convenience thing - I am not fully aware of the rendering architecture and upcoming changes to it but the idea is to include a task called `export:mp4` which can be invoked from the root of the project like `npm run export:mp4`and is included in the `scripts` entry of `package.json` generated by the `init` command. This will lower the barrier to entry for newer users. As part of this feature, we also update the _Quick start_ guide with an optional section about exporting the rendered animation to MP4

**Proposed solution**
We include a `scripts` entry into the project created by the `init` command that:
1. Detects `ffmpeg` is installed, if not errors out with an information warning/error message.
1. Changes into `output/project` directory.
2. Generates an MP4 with something like `ffmpeg -framerate 60 -pattern_type glob -i '*.png' -c:v libx264 -pix_fmt yuv420p output.mp4`
3. Removes all the PNGs afterwards.

The last part is debatable or could be another task such as `export:mp4:noclean` or something. 

**Considered alternatives**
Alternative would be for the users to add such an entry themselves.

**Comment by aarthificial** [comment] 2023-02-26 18:20
This issue is a duplicate of #4 and - with #402 being just around the corner - I don't see the point in implementing it.
We'll have a proper, customizable mp4 rendering really soon.
Here's my current stance on this topic from a recent discord conversation:

---

To expand on that, I'm motivated to get some better export options in Motion Canvas because it's clear that many people are struggling with this.
I'd even say that, together with the presentation mode, this is my main focus at the moment.

I desperately don't want to include ffmpeg as a dependency in the main mono repo because npm is awful as it is and there's nothing worse than `npm install` falling because: "Oops, looks like there are no precompiled binaries for your architecture, try compiling it yourself :)" (Of course, to make things fun, the actual error message is "python3 is not recognized as an internal or external command")

I can deal with that, but a new contributor who just wants to boot up the documentation website locally may find it really discouraging.
So the current plan is to allow people to create their own plugins with different exporters and just add them to the config:
```ts
import {defineConfig} from 'vite';
import motionCanvas from '@motion-canvas/vite-plugin';
import ffmpegPlugin from '@motion-canvas/ffmpeg';

export default defineConfig({
  plugins: [
    motionCanvas(),
    ffmpegPlugin(),
  ],
});
```
`npm init @motion-canvas` would also be extended with an option to include this by default.

This way `@motion-canvas/ffmpeg` could be its own repo with its own maintainers who would be much more knowledgeable about ffmpeg/encoding than I am.

**Closed** 2023-02-26 18:27 UTC
Labels: c-duplicate

**Comment by mohsinhijazee** [comment] 2023-02-26 19:32
Okay, I might have seen #4 and would have forgotten. And yes, the plugin architecture is more neat and proper rather than a `scripts` thingy so shouldn't rush into that.
