### ISSUE TITLE
Adding opacity to Latex component makes it low resolution

### ISSUE THREAD

**Issue by Azuryllis** [motion-canvas/motion-canvas#459] opened 2023-03-02 06:44 UTC
**Describe the bug**
Adding opacity directly to a Latex component makes the result extremely low resolution after scaling.

**To Reproduce**

```ts
view.add(
	<>
		<Latex tex={"\\color{white} test"} scale={10} y={-80 * 3} />
		<Latex tex={"\\color{white} test"} scale={10} y={0} opacity={0.5} />
		<Rect opacity={0.5}>
			<Latex tex={"\\color{white} test"} scale={10} y={80 * 3} />
		</Rect>
	</>
);
yield;
```

**Expected behavior**
The middle LaTeX "test" is an image of the same quality as the above and below LaTeX "test".

**Package versions (please complete the following information):**

- core: [3.0.0]
- 2d: [3.0.2]

**Additional Context**
Tried making Latex fade in and fade out and it just looks _bad_, work around is to wrap inside a Rect and animate that opacity.
![000447](https://user-images.githubusercontent.com/105183366/222351343-f2b034dd-57f4-46e3-830a-0b7690098528.png)

**Comment by aarthificial** [comment] 2023-03-03 11:45
Closing this as a duplicate of #342

**Closed by aarthificial** 2023-03-03 11:45 UTC
