### ISSUE TITLE
Create a docker image

### ISSUE THREAD

**Issue by Ferax-Hp** [motion-canvas/motion-canvas#400] opened 2023-02-22 15:39 UTC
**Description**
People that works with docker has to create his own image, this could be slower for people that works in multiple places, and don´t carry this own computer every where.

**Proposed solution**
Create a official image for the application, this way the people that is going to used it, can get a faster implementation of it.

**Considered alternatives**
Also you can create a docket compose, if you don´t want to pull de image on docker hub 

**Additional context**
There´s not additional, it´s just docker.

Thanks for read this, and also, sorry for my bad English.

**Comment by aarthificial** [comment] 2023-02-22 23:02
Seems like a duplicate of #188

**Closed by aarthificial** 2023-02-22 23:02 UTC
