### ISSUE TITLE
Shapes inside the `Camera` component are cropped when their opacity is set to values other than `1`

### ISSUE THREAD

**Issue by iusedtodraw** [motion-canvas/motion-canvas#1136] opened 2024-12-06 17:34 UTC
## Reproducing 

```ts
export default makeScene2D(function* (view) {
  view.add(
    <Camera>
      <Rect
        fill={"red"}
        size={size}
      />
      <Circle
        fill={"white"}
        size={size}
        opacity={0.5}
        x={100}
        y={100}
      />
    </Camera>
  );
});
```

![actual](https://github.com/user-attachments/assets/c9f97322-aa25-438a-86a9-13a6e13a1403)

## Expected behavior

![expected](https://github.com/user-attachments/assets/3b163226-65a9-486f-a504-9f1bee046b52)

## Package versions

- core: 3.17.0
- ui: 3.17.0

## Additional context

Here’s how it looks when the rendering scale is set to 0.25x:

![quarter-scale](https://github.com/user-attachments/assets/96c06daf-42dd-4df1-a756-7a65d2da5df4)

**Comment by aarthificial** [comment] 2024-12-14 21:25
Sadly this is a known issue that's yet to be fixed
Closing it as duplicate of #1057

**Closed by aarthificial** 2024-12-14 21:25 UTC
Labels: b-bug
